/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type Bank struct {

	// bank branch code
	Branch string `json:"branch,omitempty"`

	// bank account
	Account string `json:"account,omitempty"`

	// bank account state
	State string `json:"state,omitempty"`
}
