/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// get all available currencies.
type Currency struct {

	// unique currency id, check /api/v2/currencies for available currencies
	Id string `json:"id,omitempty"`

	// fixed precision of the currency
	Precision int32 `json:"precision,omitempty"`
}
