/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type MemberDocs struct {

	// ID photo front status
	PhotoIdFrontState string `json:"photo_id_front_state,omitempty"`

	// ID photo back status
	PhotoIdBackState string `json:"photo_id_back_state,omitempty"`

	// supplemental document status
	CellphoneBillState string `json:"cellphone_bill_state,omitempty"`

	// selfie status
	SelfieWithIdState string `json:"selfie_with_id_state,omitempty"`
}
