/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// get your profile and accounts infomation
type Member struct {

	// unique serial number
	Sn string `json:"sn,omitempty"`

	// user name
	Name string `json:"name,omitempty"`

	// user language
	Language string `json:"language,omitempty"`

	// valid phone set
	PhoneSet bool `json:"phone_set,omitempty"`

	// phone country code
	CountryCode string `json:"country_code,omitempty"`

	// taiwanese identity number
	IdentityNumber string `json:"identity_number,omitempty"`

	// invoice carrier id
	InvoiceCarrierId string `json:"invoice_carrier_id,omitempty"`

	// invoice carrier type
	InvoiceCarrierType string `json:"invoice_carrier_type,omitempty"`

	// is deleted
	IsDeleted bool `json:"is_deleted,omitempty"`

	// is frozen
	IsFrozen bool `json:"is_frozen,omitempty"`

	// is activated
	IsActivated bool `json:"is_activated,omitempty"`

	// is user profile verified
	ProfileVerified bool `json:"profile_verified,omitempty"`

	// is kyc approved
	KycApproved bool `json:"kyc_approved,omitempty"`

	// member kyc state: unverified, verifying, profile_verifying, verified, rejected
	KycState string `json:"kyc_state,omitempty"`

	// user mobile phone number
	PhoneNumber string `json:"phone_number,omitempty"`

	// is user aggreement checked
	UserAgreementChecked bool `json:"user_agreement_checked,omitempty"`

	// which tou version user agree with
	UserAgreementVersion string `json:"user_agreement_version,omitempty"`

	Bank *Bank `json:"bank,omitempty"`

	Documents *MemberDocs `json:"documents,omitempty"`

	// user email
	Email string `json:"email,omitempty"`

	Accounts []Account `json:"accounts,omitempty"`

	// type_guest, type_coin_1, type_coin_2, type_fiat
	MemberType string `json:"member_type,omitempty"`

	// member level
	Level int32 `json:"level,omitempty"`
}
