/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// get a specific order.
type Order struct {

	// unique order id
	Id int32 `json:"id,omitempty"`

	// 'sell' or 'buy'
	Side string `json:"side,omitempty"`

	// 'limit', 'market', 'stop_limit', or 'stop_market'
	OrdType string `json:"ord_type,omitempty"`

	// price of a unit
	Price string `json:"price,omitempty"`

	// price to trigger a stop order
	StopPrice string `json:"stop_price,omitempty"`

	// average execution price
	AvgPrice string `json:"avg_price,omitempty"`

	// 'wait', 'done', 'cancel', or 'convert'; 'wait' means waiting for fulfillment; 'done' means fullfilled; 'cancel' means cancelled; 'convert' means the stop order is triggered
	State string `json:"state,omitempty"`

	// market id, check /api/v2/markets for available markets
	Market string `json:"market,omitempty"`

	// created timestamp (second)
	CreatedAt int32 `json:"created_at,omitempty"`

	// total amount to sell/buy, an order could be partially executed
	Volume string `json:"volume,omitempty"`

	// remaining volume
	RemainingVolume string `json:"remaining_volume,omitempty"`

	// executed volume
	ExecutedVolume string `json:"executed_volume,omitempty"`

	// trade count
	TradesCount int32 `json:"trades_count,omitempty"`
}
