/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// The addresses could be empty before generated, please call POST /deposit_addresses in that case
type PaymentAddress struct {

	// currency id
	CompositeCurrency string `json:"composite_currency,omitempty"`

	// currency transfer standard, nil if only 1 version supported
	Version string `json:"version,omitempty"`

	// internal code for the currency
	Currency string `json:"currency,omitempty"`

	// deposit address, nil when generating or deposit suspended
	Address string `json:"address,omitempty"`
}
