/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// get ticker of all markets
type Tickers struct {

	Btctwd *Ticker `json:"btctwd,omitempty"`

	Ethtwd *Ticker `json:"ethtwd,omitempty"`

	Ltctwd *Ticker `json:"ltctwd,omitempty"`

	Mithtwd *Ticker `json:"mithtwd,omitempty"`

	Bchtwd *Ticker `json:"bchtwd,omitempty"`

	Usdttwd *Ticker `json:"usdttwd,omitempty"`

	Ethbtc *Ticker `json:"ethbtc,omitempty"`

	Mitheth *Ticker `json:"mitheth,omitempty"`

	Trxtwd *Ticker `json:"trxtwd,omitempty"`

	Trxbtc *Ticker `json:"trxbtc,omitempty"`

	Trxeth *Ticker `json:"trxeth,omitempty"`

	Trxusdt *Ticker `json:"trxusdt,omitempty"`

	Btcusdt *Ticker `json:"btcusdt,omitempty"`

	Ethusdt *Ticker `json:"ethusdt,omitempty"`

	Bchusdt *Ticker `json:"bchusdt,omitempty"`

	Ltcusdt *Ticker `json:"ltcusdt,omitempty"`

	Mithbtc *Ticker `json:"mithbtc,omitempty"`

	Mithusdt *Ticker `json:"mithusdt,omitempty"`

	Cccxbtc *Ticker `json:"cccxbtc,omitempty"`

	Cccxeth *Ticker `json:"cccxeth,omitempty"`

	Cccxtwd *Ticker `json:"cccxtwd,omitempty"`

	Cccxusdt *Ticker `json:"cccxusdt,omitempty"`

	Eosbtc *Ticker `json:"eosbtc,omitempty"`

	Eoseth *Ticker `json:"eoseth,omitempty"`

	Eostwd *Ticker `json:"eostwd,omitempty"`

	Eosusdt *Ticker `json:"eosusdt,omitempty"`

	Palbtc *Ticker `json:"palbtc,omitempty"`

	Paleth *Ticker `json:"paleth,omitempty"`

	Paltwd *Ticker `json:"paltwd,omitempty"`

	Batbtc *Ticker `json:"batbtc,omitempty"`

	Bateth *Ticker `json:"bateth,omitempty"`

	Battwd *Ticker `json:"battwd,omitempty"`

	Batusdt *Ticker `json:"batusdt,omitempty"`

	Zrxbtc *Ticker `json:"zrxbtc,omitempty"`

	Zrxeth *Ticker `json:"zrxeth,omitempty"`

	Zrxtwd *Ticker `json:"zrxtwd,omitempty"`

	Zrxusdt *Ticker `json:"zrxusdt,omitempty"`

	Gntbtc *Ticker `json:"gntbtc,omitempty"`

	Gnteth *Ticker `json:"gnteth,omitempty"`

	Gnttwd *Ticker `json:"gnttwd,omitempty"`

	Gntusdt *Ticker `json:"gntusdt,omitempty"`

	Omgbtc *Ticker `json:"omgbtc,omitempty"`

	Omgeth *Ticker `json:"omgeth,omitempty"`

	Omgtwd *Ticker `json:"omgtwd,omitempty"`

	Omgusdt *Ticker `json:"omgusdt,omitempty"`

	Kncbtc *Ticker `json:"kncbtc,omitempty"`

	Knceth *Ticker `json:"knceth,omitempty"`

	Knctwd *Ticker `json:"knctwd,omitempty"`

	Kncusdt *Ticker `json:"kncusdt,omitempty"`
}
