/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// get recent trades on market, sorted in reverse creation order
type Trade struct {

	// trade id
	Id int32 `json:"id,omitempty"`

	// strike price
	Price string `json:"price,omitempty"`

	// traded volume
	Volume string `json:"volume,omitempty"`

	// total traded amount
	Funds string `json:"funds,omitempty"`

	// market id
	Market string `json:"market,omitempty"`

	// created timestamp (second)
	CreatedAt int32 `json:"created_at,omitempty"`

	// 'bid' or 'ask', according to maker
	Side string `json:"side,omitempty"`

	// order related to you
	OrderId int32 `json:"order_id,omitempty"`
}
