/*
 * MAX RESTful API List
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// get details of a specific withdraw
type Withdrawal struct {

	// unique withdraw id
	Uuid string `json:"uuid,omitempty"`

	// currency id
	Currency string `json:"currency,omitempty"`

	// withdraw amount
	Amount string `json:"amount,omitempty"`

	// withdraw fee
	Fee string `json:"fee,omitempty"`

	// transaction id
	Txid string `json:"txid,omitempty"`

	// created timestamp (second)
	CreatedAt int32 `json:"created_at,omitempty"`

	// lastest updated timestamp (second)
	UpdatedAt int32 `json:"updated_at,omitempty"`

	// current state
	State string `json:"state,omitempty"`
}
